// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-cAwUkC3imQ8h41pmcR_qJ3NLo3TX4FM',
    appId: '1:350620314065:web:83b2a950762def2c74d8f0',
    messagingSenderId: '350620314065',
    projectId: 'cafebooking-9a2cd',
    authDomain: 'cafebooking-9a2cd.firebaseapp.com',
    storageBucket: 'cafebooking-9a2cd.appspot.com',
    measurementId: 'G-89E7Z110ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDgCmr1urCqrbGfbJ7dZNaL18hB1L6ys',
    appId: '1:350620314065:android:b9a3bbaf124df16774d8f0',
    messagingSenderId: '350620314065',
    projectId: 'cafebooking-9a2cd',
    storageBucket: 'cafebooking-9a2cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-cdX1dBrl1ZDsbZ10V7xb-7sk701Rac',
    appId: '1:350620314065:ios:f262103649f0e10774d8f0',
    messagingSenderId: '350620314065',
    projectId: 'cafebooking-9a2cd',
    storageBucket: 'cafebooking-9a2cd.appspot.com',
    iosClientId: '350620314065-nr5m8kffco1len7mm0p7tcrjcioadd0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-cdX1dBrl1ZDsbZ10V7xb-7sk701Rac',
    appId: '1:350620314065:ios:f262103649f0e10774d8f0',
    messagingSenderId: '350620314065',
    projectId: 'cafebooking-9a2cd',
    storageBucket: 'cafebooking-9a2cd.appspot.com',
    iosClientId: '350620314065-nr5m8kffco1len7mm0p7tcrjcioadd0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeBooking',
  );
}
